title = "Randy Ridenour"
baseURL = "http://randyridenour.net/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = " "
  facebook = "randy.ridenour"
  twitter = "randyridenour"
  instagram = ""
  youtube = ""
  github = "rlridenour"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
