baseurl = "http://randyridenour.net"
languageCode = "en-us"
title = "Randy Ridenour"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "rlridenour"

[params]
	subtitle = ""
	[params.author]
		name = "Randy Ridenour"
		# avatar = "/images/avatar.jpg"
		bio = "An elegant, responsive theme for Hugo"
		github = "rlridenour"
	[params.image]
	  feature = "/images/banner/DT84.jpg"
	  # credit = "dargadgetz"
	  # creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
