baseurl = "http://randyridenour.net/"
copyright = "&copy; 2017 Randy Ridenour"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disqusShortname = "rlridenour"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
googleAnalytics = "57227029"
publishDir = "../public"
theme = "academic"
title = "Randy Ridenour"
[blackfriday]
hrefTargetBlank = true
[languages.en]
languageCode = "en-us"
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6
[[menu.main]]
name = "Teaching"
url = "#teaching"
weight = 5
[[menu.main]]
name = "Projects"
url = "#projects"
weight = 4
[[menu.main]]
name = "Posts"
url = "#posts"
weight = 3
[[menu.main]]
name = "Home"
url = "#about"
weight = 1
[params]
address = "500 W. University St. Shawnee, OK, USA"
avatar = "manuscript.jpg"
custom_css = ["ed.css"]
custom_js = []
date_format = "Mon, Jan 2, 2006"
email = "rlridenour@gmail.com"
gravatar = false
highlight = true
highlight_languages = ["markdown", "tex", "lisp"]
keybase = ""
math = true
name = "Randy Ridenour"
office_hours = ""
organization = "Oklahoma Baptist University"
organization_url = "http://www.okbu.edu"
phone = "405 878 4432"
publication_types = ["Uncategorized", "Conference proceedings", "Journal", "Work in progress", "Technical report", "Book", "Book chapter"]
role = "Associate Professor of Philosophy"
sharing = true
skype = ""
telegram = ""
[[params.social]]
icon = "envelope"
icon_pack = "fa"
link = "mailto:rlridenour@gmail.com"
[[params.social]]
icon = "twitter"
icon_pack = "fa"
link = "//twitter.com/randyridenour"
[[params.social]]
icon = "github"
icon_pack = "fa"
link = "//github.com/rlridenour/"
[taxonomies]
category = "categories"
publication_type = "publication_types"
tag = "tags"
