baseurl = "http://randyridenour.net"
languageCode = "en-us"
title = "Randy Ridenour"
theme = "tale"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "rlridenour"

[params]
	subtitle = ""
	[params.author]
		name = "Randy Ridenour"
		# avatar = "/images/avatar.jpg"
		bio = "Associate Professor of Philosophy, Oklahoma Baptist University"
		github = "rlridenour"
        twitter = "randyridenour"
        facebook = "randy.ridenour"
	[params.image]
	  feature = "/images/banner/DT84.jpg"
